export default {
  created: 1573148914000,
  duration: 7200000,
  id: "mrkxmrybcgbsb",
  name: "ReactJS @ Virgin Pulse",
  rsvp_limit: 100,
  date_in_series_pattern: false,
  status: "upcoming",
  time: 1586907000000,
  local_date: "2020-04-14",
  local_time: "18:30",
  rsvp_close_offset: "PT1H45M",
  updated: 1583891810000,
  utc_offset: -18000000,
  waitlist_count: 0,
  yes_rsvp_count: 54,
  venue: {
    id: 26856955,
    name: "Virgin Pulse",
    lat: 32.892181396484375,
    lon: -96.76834869384766,
    repinned: false,
    address_1: "10670 N Central Expy",
    address_2: "Suite 400",
    city: "Dallas",
    country: "us",
    localized_country_name: "USA",
    zip: "75231",
    state: "tx"
  },
  group: {
    created: 1455206836000,
    name: "ReactJS Dallas",
    id: 19555115,
    join_mode: "open",
    lat: 32.790000915527344,
    lon: -96.80000305175781,
    urlname: "ReactJSDallas",
    who: "React Devs",
    localized_location: "Dallas, TX",
    state: "TX",
    country: "us",
    region: "en_US",
    timezone: "US/Central"
  },
  link: "https://www.meetup.com/ReactJSDallas/events/mrkxmrybcgbsb/",
  description:
    '<p>Everyone has seen React in action. If you have used Facebook, Instagram, Airbnb, Dropbox, or IMDb, then you have used React.</p> <p>Our team at Call-Em-All created the popular open-source library Material-UI (<a href="http://www.material-ui.com" class="linkified">http://www.material-ui.com</a>), and we use React every day.</p> <p>Bring your laptop with your favorite text editor, dig into the React docs (<a href="http://facebook.github.io/react/" class="linkified">http://facebook.github.io/react/</a>) to get started learning, and come ready with questions that we can tackle together.</p> <p>Pizza/drinks at 6:15pm and feel free to stay later for more conversations!</p> <p>---------<br/>Join our Slack channel to tell us about your open jobs, upcoming events, fun blog posts, and code issues that Stack Overflow cannot solve!</p> <p><a href="https://join.slack.com/t/reactjs-dallas/shared_invite/enQtMzQ0NDY2NDQ3MzQ3LTc3YWI2Y2M4MDJiNjQyYjczYTE5YzM5OTBiMGM1YWNiMmE5YmE1ZjM2N2UxODMyNTE1NTAzNzlhMzliNTUyMGY" class="linkified">https://join.slack.com/t/reactjs-dallas/shared_invite/enQtMzQ0NDY2NDQ3MzQ3LTc3YWI2Y2M4MDJiNjQyYjczYTE5YzM5OTBiMGM1YWNiMmE5YmE1ZjM2N2UxODMyNTE1NTAzNzlhMzliNTUyMGY</a><br/>--------<br/>If you want to support our fun and informative events, then you can now make a contribution to our ReactJS Dallas User Group open collective!</p> <p><a href="https://opencollective.com/reactjs-dallas" class="linkified">https://opencollective.com/reactjs-dallas</a></p> ',
  visibility: "public",
  member_pay_fee: false
};
